name: CI

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    types:
      - opened
      - synchronize
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        runs-on:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        cabal:
          - latest
        ghc:
          - "9.12"
          - "9.10"
          - "9.8"
    runs-on: ${{ matrix.runs-on }}
    outputs:
      cabal2json: ${{ steps.upload-artifact.outputs.artifact-id }}
    steps:
      - name: Set artifact name to cabal2json-ghc-${{ matrix.ghc }}-${{ runner.arch }}-${{ runner.os }}
        run: echo "FULLNAME=cabal2json-ghc-${{ matrix.ghc }}-${{ runner.arch }}-${{ runner.os }}" >> $GITHUB_ENV

      - uses: actions/checkout@v4

      - name: Install GHC and cabal
        uses: haskell/ghcup-setup@v1.2
        with:
          ghc: ${{ matrix.ghc }}
          cabal: ${{ matrix.cabal }}

      - name: Update Hackage index
        run: cabal update

      - name: Build
        run: cabal build

      - name: Test
        run: cabal run -- golden-tests

      - name: Move files around
        run: |
          mkdir -p out
          mv $(cabal list-bin cabal2json) out/${{ env.FULLNAME }}

      - id: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.FULLNAME }}
          path: out/${{ env.FULLNAME }}

  release:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true
      - run: gh release create --draft ${{ github.ref_name }} artifacts/*
