name: Release CI

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    container: benz0li/ghc-musl

    steps:
      - uses: actions/checkout@v4

      - run: cabal update

      - run: cabal build

      - run: cabal test

      - run: gh release create ${{ github.refname }} --generate-notes $(cabal list-bin cabal2json)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
